name: Run Go Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
       go mod download
       sudo apt-get install -y unzip
    
    - name: Download blockchain data
      run: |
        curl -o data/deneb_holesky_beacon_state_2227472.ssz.zip https://dviu8zszosyat.cloudfront.net/deneb_holesky_beacon_state_2227472.ssz.zip
        (cd data && unzip deneb_holesky_beacon_state_2227472.ssz.zip)

    - name: Run tests
      run: go test ./...
